### PR TITLE
Allow a Copy impl

### PR DESCRIPTION
**Pull request by WorldSEnder**
This allows a Copy impl, as already mentioned in the [Readme](https://github.com/nwtgck/stacklover-rust?tab=readme-ov-file#implement-trait-example).

It works by moving the Drop impl into the __impl_traits section and generating it only when the user has not requested a Copy impl.

A bit of a sour taste is that this has to bring back the `Clone, Copy` annotations on the storage type. It might be possible to have two separate storage types, with one not being Copy to safe-guard the non-copy types a bit more. Let me know if you think this is worth to try to avoid duplicating values.

On a related note, I've added a small test that asserts that the Drop impls are actually run on types that need it ^^

I have thought about asserting that the inner type doesn't need a drop with `NO_DROP` with

```rust
    ( $struct_name:ident, # NO_DROP ) => {
        const _: () = {
            const fn assert_no_drop<T>(_: fn() -> T) {
                assert!(!::core::mem::needs_drop::<T>())
            }
            assert_no_drop(__stacklover_inner_unreachable);
        };
    };
```

but I can't find a relevant section that `core::mem::needs_drop` is guaranteed to return `false` if the type is actually `Copy`, so my current assumption is that the above might lead to spurious assertion failures.

### CODE REVIEW

**Comment by nwtgck** [comment]
Adding `# NO_DROP` when `Copy` specified is great idea!

> I have thought about asserting that the inner type doesn't need a drop with NO_DROP with ...

Thank you for considering static assetion. How about asserting the inner type does not implement `Drop` like the following?

```rs
use std::rc::Rc;

trait MaybeCannotInfer<S> {}
impl<T> MaybeCannotInfer<()> for T {}
impl<T: Drop> MaybeCannotInfer<((), ())> for T {}

const fn assert_not_drop<T: MaybeCannotInfer<S>, S>() {}
assert_not_drop::<i32, _>();

// assert_not_drop::<Rc<i32>, _>();
// ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type of the type parameter `S` declared on the function `assert_not_drop`
```

**Comment by WorldSEnder** [comment]
> ```rust
> impl<T: Drop> MaybeCannotInfer<((), ())> for T {}
> ```

This famously does not do what you think it does. Not every type that needs to be dropped implements Drop. The compiler emits the following warning for the above code:

> warning: bounds on `T: Drop` are most likely incorrect, consider instead using `std::mem::needs_drop` to detect whether a type can be trivially dropped

The [associated lint docs](https://doc.rust-lang.org/stable/nightly-rustc/rustc_lint/traits/static.DROP_BOUNDS.html) explain the following:

> Drop bounds do not actually indicate whether a type can be trivially dropped or not, because a composite type containing Drop types does not necessarily implement Drop itself. Naïvely, one might be tempted to write an implementation that assumes that a type can be trivially dropped while also supplying a specialization for T: Drop that actually calls the destructor. However, this breaks down e.g. when T is String, which does not implement Drop itself but contains a Vec, which does implement Drop, so assuming T can be trivially dropped would lead to a memory leak here.

```rust
assert_not_drop::<String, _>(); // No ambiguity error here :/
```

As alluded `std::mem::needs_drop` might work for this application, but it can be overly conservative and return `true` even for types that do not need to be dropped.

**Comment by nwtgck** [comment]
I see.

How about adding the `Copy` assertion again in `# NO_DROP`? This ensures the inner type implements `Copy`.
```rs
const _: fn() = || {
    fn assert_trait<T: ::core::marker::Copy>(_: T) {}
    assert_trait(__stacklover_inner_unreachable());
};
```

**Comment by WorldSEnder** [comment]
> How about adding the `Copy` assertion again in `# NO_DROP`? This ensures the inner type implements `Copy`.

If you like. One comment about the `#` here: This makes sure that this part of the macro is not accessible to users who invoke `define_struct!`. `define_struct!` matches identifiers, which `#` is not. So far, I consider not emitting a `Drop` impl implementation detail that the user can't control, so the reasoning is that the assertion is already there in the part that emits the `Copy` impl in the first place and would always be duplicate. I.e.

https://github.com/nwtgck/stacklover-rust/pull/4/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R403-R406

is the only place that passes `NO_DROP`.

**Comment by nwtgck** [comment]
> One comment about the # here

Thanks. Now I understood the intension using `#`, which is not ident.

**Comment by nwtgck** [comment]
> This allows a Copy impl, as already mentioned in the [Readme](https://github.com/nwtgck/stacklover-rust?tab=readme-ov-file#implement-trait-example).

This was mistake... But I will merge this and it becomes true.

**Review by nwtgck — APPROVED** [review]

**Comment by nwtgck** [comment]
Thank you so much again!

**Comment by WorldSEnder** [comment]
> This was mistake... But I will merge this and it becomes true.

I only mentioned it to address why the PR doesn't contain additional documentation ^^ Thanks for your fast and critical review, very much appreciated.

**Comment by nwtgck** [comment]
> I only mentioned it to address why the PR doesn't contain additional documentation ^^

Actually, I fetched the PR and tried to write Copy documentation and noticed Copy documentation already written... Then, I understood the meaning of "as already mentioned in the [Readme](https://github.com/nwtgck/stacklover-rust?tab=readme-ov-file#implement-trait-example)."

**Pull request merged**
